name: Publish Python Package

on:
  push:
    # Trigger when you push tags like v0.1.0, v1.2.3, etc.
    tags:
      - 'v0.1.0'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # If you set up a GitHub Actions environment named 'pypi', include:
    environment: pypi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build distributions
        run: |
          python -m build

      - name: Publish to PyPI
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
